### ISSUE TITLE
GSoC 2019

### ISSUE THREAD

**Issue by shivanshu1333** [extenly/qtqc2_calendar#1]
Hii,
This is Shivanshu from Indian Institute of Technology.
I would love to work with GFOSS in GSOC 19 for the project "Port Qt Quick Controls Calendar widget to Qt Quick Controls 2 module" as the skill set required to continue the project matches with my interest. I have been doing WebDev since past two years and contributed to many projects/orgs since then (Currently member of Fossasia and Cobnagi).
I found this repository completely empty, please help me with the initial proceedings so that I can make some initial commits before GSoC period starts. @extenly @Alexandra Betouni please prove essential links and info.
Thank you!

**Comment by extenly** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Hello Shivanshu,Thank you for your interest! Could you please also send your application to gsoc-developers@ellak.gr so that the organization is also aware of your candidature for this project?I will send you more information and guidance later this week but nevertheless, the project has to be approved first.Regards,Alexandra                                                                                                                                                                           From: notifications@github.comSent: March 12, 2019 08:00To: qtqc2_calendar@noreply.github.comReply-to: reply@reply.github.comCc: alexandra.betouni@extenly.com; mention@noreply.github.comSubject: [extenly/qtqc2_calendar] GSoC 2019 (#1)  Hii,
This is Shivanshu from Indian Institute of Technology.
I would love to work with GFOSS in GSOC 19 for the project "Port Qt Quick Controls Calendar widget to Qt Quick Controls 2 module" as the skill set required to continue the project matches with my interest. I have been doing WebDev since past two years and contributed to many projects/orgs since then (Currently member of Fossasia and Cobnagi).
I found this repository completely empty, please help me with the initial proceedings so that I can make some initial commits before GSoC period starts. @extenly @alexandra Betouni please prove essential links and info.
Thank you!

**Comment by shivanshu1333** [comment]
@extenly is there any way to contact the mentor Directly. I couldn't find the email of Alexandra betouni.
